### ISSUE TITLE
Baud Rate Wont Switch

### ISSUE THREAD

**Issue by ubergeekzone** [NefMoto/NefMotoOpenSource#17] opened 2020-01-16 22:00 UTC
i set baud rate to 38400, still connects at 10400. Any ideas?

**Comment by nyetwurk** [comment] 2020-01-16 22:03
init always happens at 10400, the transfer should happen at the set baudrate.

**Comment by nyetwurk** [comment] 2020-01-16 22:03
see also #2

**Comment by ubergeekzone** [comment] 2020-01-16 22:07
@nyetwurk this is exactly what i thought after reviewing the code. This was working prefect until we loaded a custom tune. Werid part is VCDS connects to ecu and car runs prefect. Nefmoto will not read ecu info, dtcs or load tunes anymore. Any thoughts?

**Comment by nyetwurk** [comment] 2020-01-16 22:11
if you reflash with stock, does it he problem go away?
otherwise, whatever tune you are loading is either deliberately or inadvertently disabling upload.

**Comment by ubergeekzone** [comment] 2020-01-16 22:12
@nyetwurk let me try to load stock tune and see.

**Comment by ubergeekzone** [comment] 2020-01-16 22:16
@nyetwurk nefmoto won't load ecu info, dtcs or upload any tunes at all. this is working before the new tune. so i guess its bricked somehow?

**Comment by nyetwurk** [comment] 2020-01-16 22:17
Yes. You will need bootmode to recover it.
Is this your own tune? If not, trash it.

**Comment by ubergeekzone** [comment] 2020-01-16 22:18
it was done by a tuner you are friends with.

**Comment by nyetwurk** [comment] 2020-01-16 22:18
Might want to talk to that person.

**Comment by ubergeekzone** [comment] 2020-01-16 22:19
@nyetwurk we are talking, i am trying to prove to him its the tune though. thats why i reached out to you.

**Comment by nyetwurk** [comment] 2020-01-16 22:20
What is the P/N of the ecu?

We should continue this on nef if possible

**Comment by ubergeekzone** [comment] 2020-01-16 22:21
4D0 907 560 AE

**Comment by nyetwurk** [comment] 2020-01-16 22:23
Should be fine, unless it is affected by the deathcode bug
http://nefariousmotorsports.com/forum/index.php?topic=981.0title=

**Comment by ubergeekzone** [comment] 2020-01-16 22:24
@nyetwurk not a deathcode bug issue, we had loaded many other tunes based on my stock tune before. The tuner wrote his own tune to bypass some issues and now we are facing this. Like i said VCDS still connects and works and car runs prefect. Just trying to load a tune revision.

**Comment by nyetwurk** [comment] 2020-01-16 22:26
Unfortunately you will likely need a bench flasher and bootmode to recover the ecu at this point, unless something else is amiss (e.g. flakey k line, low bat voltage, etc).

you can try progressively lower baudrates, not sure what the OP baud issue was or if that is related.

**Comment by ubergeekzone** [comment] 2020-01-16 22:29
@nyetwurk i have a bench setup, thats not an issue. its nothing in the car related it does the same thing on my bench setup. lower baudrates have no effect. we were using 38400 and that was working till now.

**Comment by nyetwurk** [comment] 2020-01-16 22:31
Just saying, to conclusively prove it is one version over another, flash them. If you can't flash, use bootmode.

**Comment by ubergeekzone** [comment] 2020-01-16 22:39
i will need to use galletto boot mode? or nefmoto?

**Comment by nyetwurk** [comment] 2020-01-16 22:59
galletto. nef does not have bootmode support

**Comment by ubergeekzone** [comment] 2020-01-17 00:33
@nyetwurk we used galletto and got new tune loaded. looks like we will have to use galletto to load tunes for now. thanks for your help.

**Comment by nyetwurk** [comment] 2020-01-17 01:05
That is VERY bad. You should not need galletto. You should narrow it down to one version.

**Comment by nyetwurk** [comment] 2024-11-21 17:53
Dupe of #2

**Closed by nyetwurk** 2024-11-21 17:53 UTC
